=== enpitsuLin/blog.enpitsuLin.xyz/src/content/friends/schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "additionalProperties": false,
  "properties": {
    "$schema": {
      "type": "string",
      "title": "Schema",
      "description": "Pointer to the schema against which this document should be validated."
    },
    "description": {
      "type": "string",
      "description": "Your website description."
    },
    "favicon": {
      "anyOf": [
        {
          "type": "string"
        },
        {
          "additionalProperties": false,
          "properties": {
            "dark": {
              "type": "string"
            },
            "light": {
              "type": "string"
            }
          },
          "required": [
            "light",
            "dark"
          ],
          "type": "object"
        }
      ],
      "description": "Your website favicon link, which can specify a different dark or light color schema."
    },
    "title": {
      "type": "string",
      "description": "Your website title."
    },
    "url": {
      "type": "string",
      "description": "Your website url"
    }
  },
  "required": [
    "title",
    "url",
    "description",
    "favicon"
  ],
  "type": "object"
}

=== enpitsuLin/blog.enpitsuLin.xyz/src/content/friends/example.json
{
  "$schema": "../schema/friends.json",
  "title": "example",
  "url": "https://github.com",
  "description": "example site description",
  "favicon": {
    "light": "https://github.githubassets.com/favicons/favicon.png",
    "dark": "https://github.githubassets.com/favicons/favicon-dark.png"
  }
}
